# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 502e80897e9f2d39c379c96573bf62e93e5675255263a47c261cd832b44e922ac15e0d8d14501d43b477b54159c649f2a8b44f7dcbf647188628493c817c4fbf

test:
  secret_key_base: ed06ad368d450014956125591fc462baa582a7de798f1a14c675ede31fa0a3080e1d97782d2dc6e39daeef7d4f923f00bdf5c908543161c950b15e9b72cd2be1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
